# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_nmf <- function(A, tol, maxit, verbose, L1, threads, w) {
    .Call(`_FastNMF_c_nmf`, A, tol, maxit, verbose, L1, threads, w)
}

